### ISSUE TITLE
late night things

### ISSUE THREAD

**Issue by gagedevs** [Hydrogen-Network/Hydrogen#16]
was bored last night, and saw your proxy was in need of some help
https://github.com/oHeckGage/hydrogen cba to make a pull req so if u wanna implement the changes do it yourself or something
also if u need hosting dm me @xgage on Discord, since u can't just use a static host

**Comment by Coding4Hours** [comment]
i can it works just try

**Comment by Coding4Hours** [comment]
but i can say thats the node version

**Comment by Coding4Hours** [comment]
thx tho

**Comment by oHeckGage** [comment]
it doesn't work though, the site cors policy is blocking access to tomp.app and tomp.app speeds and uptime in general aren't great. you should really host hydrogen on your own node app so that you have your own bare.

**Comment by Coding4Hours** [comment]
i fixed it

**Comment by Coding4Hours** [comment]
im using interstellars now
